name: Deploy to Productionname: Deploy Website



on:on:

  push:  push:

    branches: [main]    branches: [ main ]

  workflow_dispatch:  workflow_dispatch:



jobs:jobs:

  build-and-deploy:  deploy:

    runs-on: ubuntu-latest    runs-on: ubuntu-latest

    steps:    

      - uses: actions/checkout@v4    steps:

          - name: Checkout code

      - uses: actions/setup-node@v4      uses: actions/checkout@v4

        with:      

          node-version: 18    - name: Setup Node.js

          cache: npm      uses: actions/setup-node@v4

          cache-dependency-path: frontend/package-lock.json      with:

              node-version: '18'

      - name: Install and Build        cache: 'npm'

        run: |        cache-dependency-path: frontend/package-lock.json

          cd frontend        

          npm ci    - name: Install dependencies

          npm run build      working-directory: frontend

            run: npm ci

      - name: Deploy Files      

        env:    - name: Build frontend

          HOST: ${{ secrets.SFTP_HOST }}      working-directory: frontend

          USER: ${{ secrets.SFTP_USERNAME }}      run: npm run build

          PASS: ${{ secrets.SFTP_PASSWORD }}        

          DIR: ${{ secrets.ONECOM_REMOTE_DIR }}    - name: Deploy via rsync over SSH  

        run: |      run: |

          sudo apt-get update && sudo apt-get install -y lftp        # Install rsync and sshpass

          lftp -c "        sudo apt-get update

            set sftp:auto-confirm yes        sudo apt-get install -y rsync sshpass

            set ssl:verify-certificate no          

            open sftp://$USER:$PASS@$HOST        # Deploy using rsync with password authentication

            mirror --reverse --delete --verbose frontend/dist/ $DIR/        export SSHPASS="${{ secrets.SFTP_PASSWORD }}"

            bye        rsync -avz --delete \

          "          -e "sshpass -e ssh -o StrictHostKeyChecking=no -p 22" \
          frontend/dist/ \
          ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:${{ secrets.ONECOM_REMOTE_DIR }}/